# Generated by Django 5.0.6 on 2024-07-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['borrowing_date']},
        ),
    ]
