# Generated by Django 5.0.6 on 2024-07-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_alter_borrowing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-borrowing_date']},
        ),
    ]
